### ISSUE TITLE
eo_posix 0.9 doesn't compile on FreeBSD 12.2

### ISSUE THREAD

**Issue by hannesm** [ocaml-multicore/eio#502]
The error is
```
# command              ~.opam/5.0.0/bin/dune build -p eio_posix -j 1 @install
# exit-code            1
# env-file             ~.opam/log/eio_posix-26556-119cdd.env
# output-file          ~.opam/log/eio_posix-26556-119cdd.out
### output ###
# -> stderr:
# [...]
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | fatal error: too many errors emitted, stopping now [-ferror-limit=]
#  | 20 errors generated.
# Error: failed to compile program
```

**Comment by talex5** [comment]
I guess we can just remove that that.

Who is using FreeBSD 12, though? I only tested on FreeBSD 13.1 (it works there).
