### PR TITLE
eio_posix: remove dsync open flag

### LINKED ISSUE #502: eo_posix 0.9 doesn't compile on FreeBSD 12.2
The error is
```
# command              ~.opam/5.0.0/bin/dune build -p eio_posix -j 1 @install
# exit-code            1
# env-file             ~.opam/log/eio_posix-26556-119cdd.env
# output-file          ~.opam/log/eio_posix-26556-119cdd.out
### output ###
# -> stderr:
# [...]
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | /tmp/build_33ec8a_dune/ocaml-configurator17a47a/c-test-0/test.c:80:12: error: use of undeclared identifier 'O_DSYNC'
#  | fatal error: too many errors emitted, stopping now [-ferror-limit=]
#  | 20 errors generated.
# Error: failed to compile program
```

### PR DESCRIPTION
**Pull request by talex5**
FreeBSD 12 doesn't have `O_DSYNC` (though FreeBSD 13 does) and it doesn't look very useful. https://pubs.opengroup.org/onlinepubs/9699919799/help/codes.html#SIO says: "The functionality described is optional"

Reported by @hannesm.

Closes #502 (untested).

### CODE REVIEW

**Comment by talex5** [comment]
Closing in favour of #507.
